# put this file in ~/.config/clangd
# clang -v -c -xc++ /dev/null
# and replace /nix/store/..... with output from #include <...> search starts here:

# CompileFlags:
#       Add: [
#       -isystem/nix/store/kzq78n13l8w24jn8bx4djj79k5j717f1-gcc-14.3.0/include/c++/14.3.0,
#       -isystem/nix/store/gi4cz4ir3zlwhf1azqfgxqdnczfrwsr7-glibc-2.40-66-dev/include,
#       -isystem/nix/store/gj06hl0vb46kf66zpsss4gk5wphfh5lk-compiler-rt-libc-21.1.2-dev/include,
#       -isystem/nix/store/kzq78n13l8w24jn8bx4djj79k5j717f1-gcc-14.3.0/include/c++/14.3.0/x86_64-unknown-linux-gnu,
#       -isystem/nix/store/sqlnjj8c3n3si3sjnadhdbcwgrk97g2w-clang-wrapper-21.1.2/resource-root/include,
#       -isystem/nix/store/gi4cz4ir3zlwhf1azqfgxqdnczfrwsr7-glibc-2.40-66-dev/include
#       ]

CompileFlags:
      Add: [
      -isystem/home/thinky/Downloads/NixOS/rust/.devenv/profile
      ]
